cmd/tubectl: simplify unregister error message
The current output is

    Error: unregister: failed to unregister socket cdn-http, ipv4, udp:
    remove socket: lookup failed: key does not exist

Make it more succinct:

    Error: unregister: socket cdn-http:ipv4:udp doesn't exist