TUBE-28: Delay & retry dial over UNIX socket on hard errors
net.DialTimeout does not delay & retry when there is no UNIX listener.
This means we need to implement the delay & retry ourselves.

Fixes flaky tests that were failing with:

--- FAIL: TestServeAddressTypes (0.01s)
    --- FAIL: TestServeAddressTypes/serve_on_abstract_address (0.00s)
        serve_test.go:71: can't dial server at @tubectl_serve_test-2fff01b39368e8a0: max dial attempts reached
FAIL