TUBE-9: Simplify error message from newDestinationFromConn
Error message returned by newDestinationFromConn is too verbose:

=== RUN   TestRegisterFailsForUnusedFd
    register_test.go:78: tubectl -netns /proc/229/task/246/ns/net register non-socket-fd
        Error: register: can't register fd 3: destination from fd: fd is not a socket: bad file descriptor

Adding the prefix does not introduce new valuable information or serve any
purpose in this thin wrapper for newDestinationFromFd. Simply forward the
error from the function actually doing the work.